sudo: false
language: node_js
node_js:
  - 6
  - 7
  - 8
  - stable

jobs:
  include:
    - stage: Document deploy
      allow_failure: true
      script: npm run build:browser
      deploy:
        edge:
          branch: v1.8.47
        provider: pages
        skip_cleanup: true
        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
        local_dir: public

    - stage: Test
      before_script: npm install codecov
      script: npm test -- --coverage
      after_script: codecov --token=$CODECOV_TOKEN
